[2024-04-11T16:49:36.848+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T16:49:36.987+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2.save_data scheduled__2024-04-11T16:46:00+00:00 [queued]>
[2024-04-11T16:49:36.991+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2.save_data scheduled__2024-04-11T16:46:00+00:00 [queued]>
[2024-04-11T16:49:36.991+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2024-04-11T16:49:36.996+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data> on 2024-04-11 16:46:00+00:00
[2024-04-11T16:49:37.005+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1969) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T16:49:37.004+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2', 'save_data', 'scheduled__2024-04-11T16:46:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmpgansxz24']
[2024-04-11T16:49:37.006+0000] {standard_task_runner.py:63} INFO - Started process 1971 to run task
[2024-04-11T16:49:37.006+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask save_data
[2024-04-11T16:49:37.051+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2.save_data scheduled__2024-04-11T16:46:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T16:49:37.093+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T16:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T16:46:00+00:00'
[2024-04-11T16:49:37.094+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T16:49:38.824+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-11T16:49:38.824+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T16:49:38.835+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=22655381_DAG2, task_id=save_data, execution_date=20240411T164600, start_date=20240411T164936, end_date=20240411T164938
[2024-04-11T16:49:38.863+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T16:49:38.877+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T16:49:38.878+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
