[2024-04-11T15:05:40.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T15:05:40.601+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v04.create_dataset scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:05:40.605+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v04.create_dataset scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:05:40.605+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-04-11T15:05:40.611+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-04-09 17:00:00+00:00
[2024-04-11T15:05:40.620+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4598) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T15:05:40.619+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_gg_bigquery_v04', 'create_dataset', 'scheduled__2024-04-09T17:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_gg_bigquery.py', '--cfg-path', '/tmp/tmplvw7hw1u']
[2024-04-11T15:05:40.622+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask create_dataset
[2024-04-11T15:05:40.621+0000] {standard_task_runner.py:63} INFO - Started process 4600 to run task
[2024-04-11T15:05:40.660+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_gg_bigquery_v04.create_dataset scheduled__2024-04-09T17:00:00+00:00 [running]> on host a4f2bd86ee13
[2024-04-11T15:05:40.725+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='duy' AIRFLOW_CTX_DAG_ID='dag_with_gg_bigquery_v04' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T17:00:00+00:00'
[2024-04-11T15:05:40.727+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T15:05:40.749+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-11T15:05:40.750+0000] {base.py:84} INFO - Using connection ID 'gcp' for task execution.
[2024-04-11T15:05:40.796+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value retail.
[2024-04-11T15:05:40.796+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value ***-projecct.
[2024-04-11T15:05:40.796+0000] {bigquery.py:481} INFO - Creating dataset: retail in project: ***-projecct 
[2024-04-11T15:05:42.008+0000] {bigquery.py:485} INFO - Dataset created successfully.
[2024-04-11T15:05:42.037+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T15:05:42.057+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_with_gg_bigquery_v04, task_id=create_dataset, execution_date=20240409T170000, start_date=20240411T150540, end_date=20240411T150542
[2024-04-11T15:05:42.108+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T15:05:42.133+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-11T15:05:42.134+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
