[2024-04-11T15:10:05.936+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T15:10:05.948+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v04.create_dataset scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:10:05.953+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v04.create_dataset scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:10:05.953+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 5
[2024-04-11T15:10:05.962+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-04-09 17:00:00+00:00
[2024-04-11T15:10:05.972+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_gg_bigquery_v04', 'create_dataset', 'scheduled__2024-04-09T17:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_gg_bigquery.py', '--cfg-path', '/tmp/tmp00p1dinc']
[2024-04-11T15:10:05.974+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4903) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T15:10:05.974+0000] {standard_task_runner.py:63} INFO - Started process 4905 to run task
[2024-04-11T15:10:05.974+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask create_dataset
[2024-04-11T15:10:06.013+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_gg_bigquery_v04.create_dataset scheduled__2024-04-09T17:00:00+00:00 [running]> on host a4f2bd86ee13
[2024-04-11T15:10:06.066+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='duy' AIRFLOW_CTX_DAG_ID='dag_with_gg_bigquery_v04' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T17:00:00+00:00'
[2024-04-11T15:10:06.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T15:10:06.081+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-11T15:10:06.082+0000] {base.py:84} INFO - Using connection ID 'gcp' for task execution.
[2024-04-11T15:10:06.121+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value retail.
[2024-04-11T15:10:06.122+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value ***-projecct.
[2024-04-11T15:10:06.122+0000] {bigquery.py:481} INFO - Creating dataset: retail in project: ***-projecct 
[2024-04-11T15:10:07.226+0000] {bigquery.py:2045} INFO - Dataset retail already exists.
[2024-04-11T15:10:07.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T15:10:07.262+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_with_gg_bigquery_v04, task_id=create_dataset, execution_date=20240409T170000, start_date=20240411T151005, end_date=20240411T151007
[2024-04-11T15:10:07.286+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T15:10:07.313+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-11T15:10:07.314+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
